/**
 * Firestore Security Rules Test Suite (Dirty Dozen Verification)
 * Verifies that all 12 adversarial payloads in security_spec.md return PERMISSION_DENIED.
 */

export interface DirtyDozenTestCase {
  id: number;
  name: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  path: string;
  authUid: string | null;
  emailVerified: boolean;
  payload?: Record<string, unknown>;
  expectedResult: 'PERMISSION_DENIED';
}

export const dirtyDozenTestSuite: DirtyDozenTestCase[] = [
  {
    id: 1,
    name: 'Shadow Field Injection on User Profile Create',
    operation: 'create',
    path: '/users/user_1',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      uid: 'user_1',
      username: 'Alice',
      role: 'member',
      status: 'online',
      bio: 'Hello world',
      avatarColor: '#2563EB',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
      isSuperAdmin: true,
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Identity Spoofing on Room Message Create',
    operation: 'create',
    path: '/rooms/general/messages/msg_1',
    authUid: 'attacker_uid',
    emailVerified: true,
    payload: {
      roomId: 'general',
      authorUid: 'victim_uid_999',
      authorUsername: 'Victim',
      authorRole: 'member',
      text: 'Spoofed message',
      isPublic: true,
      createdAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Unauthorized Member Updating Global Ticker',
    operation: 'update',
    path: '/ticker_slots/slot_1',
    authUid: 'regular_member_uid',
    emailVerified: true,
    payload: {
      slotIndex: 1,
      text: 'Unauthorized ticker update',
      publisherUid: 'regular_member_uid',
      publisherUsername: 'RegularUser',
      publisherRole: 'vip',
      category: 'General',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Out-of-Bounds Ticker Slot (slot_8)',
    operation: 'create',
    path: '/ticker_slots/slot_8',
    authUid: 'vip_uid',
    emailVerified: true,
    payload: {
      slotIndex: 8,
      text: 'Invalid 8th slot',
      publisherUid: 'vip_uid',
      publisherUsername: 'VipUser',
      publisherRole: 'vip',
      category: 'General',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Orphaned Message Write to Non-Existent Room',
    operation: 'create',
    path: '/rooms/non_existent_room/messages/msg_1',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      roomId: 'non_existent_room',
      authorUid: 'user_1',
      authorUsername: 'Alice',
      authorRole: 'member',
      text: 'Orphan message',
      isPublic: true,
      createdAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Cross-User PII Read on users_private',
    operation: 'get',
    path: '/users_private/victim_uid',
    authUid: 'attacker_uid',
    emailVerified: true,
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Client Forged Timestamp on Bubble Message',
    operation: 'create',
    path: '/bubble_messages/bmsg_1',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      channelId: 'pulse',
      authorUid: 'user_1',
      authorUsername: 'Alice',
      authorRole: 'member',
      text: 'Forged time',
      isPublic: true,
      createdAt: '2020-01-01T00:00:00Z',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Denial-of-Wallet Oversized Message Payload',
    operation: 'create',
    path: '/rooms/general/messages/msg_oversized',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      roomId: 'general',
      authorUid: 'user_1',
      authorUsername: 'Alice',
      authorRole: 'member',
      text: 'A'.repeat(2000),
      isPublic: true,
      createdAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'ID Poisoning Attack',
    operation: 'create',
    path: '/rooms/invalid$$id!!',
    authUid: 'user_1',
    emailVerified: true,
    payload: {},
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Immutable Field Mutation on User Profile Update',
    operation: 'update',
    path: '/users/user_1',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      uid: 'different_uid',
      username: 'Alice',
      role: 'member',
      status: 'online',
      bio: 'Bio',
      avatarColor: '#2563EB',
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Value Poisoning on Update (Invalid Type)',
    operation: 'update',
    path: '/users/user_1',
    authUid: 'user_1',
    emailVerified: true,
    payload: {
      uid: 'user_1',
      username: 'Alice',
      role: 'member',
      status: 'online',
      bio: 999999,
      avatarColor: '#2563EB',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Unverified Email Spoof Attack',
    operation: 'create',
    path: '/users/spoof_uid',
    authUid: 'spoof_uid',
    emailVerified: false,
    payload: {
      uid: 'spoof_uid',
      username: 'AdminSpoofer',
      role: 'admin',
      status: 'online',
      bio: 'Spoofing admin',
      avatarColor: '#2563EB',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
];
